name: Node ESLint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: export NODE_ENV=development
      - run: npm ci
      - run: eslint "**/*.js" --ignore-pattern node_modules/
